name: .NET

on:
  push:
    paths:
      - apis/poi/**
      - .github/workflows/dotnet.yml
  pull_request:
    branches: [ master ]
    paths:
      - apis/poi/**
      - .github/workflows/dotnet.yml

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with: 
        dotnet-version: '3.1.202'
        
    - name: Restore dependencies 
      run: dotnet restore apis/poi/web/poi.csproj
    
    - name: Test
      run: dotnet test apis/poi/tests/UnitTests/UnitTests.csproj --verbosity normal
        
    - name: Build
      run: dotnet build apis/poi/web/poi.csproj --no-restore
        
    - name: Test
      run: dotnet test apis/poi/tests/IntegrationTests/IntegrationTests.csproj --verbosity normal

    - uses: nashmaniac/create-issue-action@v1.1
      if: ${{ failure() }} # only run when this job is failed.
      name: Create Issue Action
      with:
          title: Build Failed
          token: ${{secrets.GITHUB_TOKEN}}
          assignees: ${{github.actor}}
          labels: Build failed, help needed
          body: Workflow failed for commit ${{github.sha}}

  docker-build-and-deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: build-and-test
    env:
      registery: openhackw1l12y49acr.azurecr.io
      app: devopsoh/api-poi
      dockerpath: apis/poi/web
      webappname: openhackw1l12y49poi
    
    steps:
    # checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@master
            
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ env.registery }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - run: |
        docker build ${{ env.dockerpath }} -t ${{ env.registery }}/${{ env.app }}:${{ github.run_number }}
        docker push ${{ env.registery }}/${{ env.app }}:${{ github.run_number }}
  
    - name: 'Deploy to Azure Web App for Container'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.webappname }} 
        images: ${{ env.registery }}/${{ env.app }}:${{ github.run_number }}

    - uses: nashmaniac/create-issue-action@v1.1
      if: ${{ failure() }} # only run when this job is failed.
      name: Create Issue Action
      with:
          title: Build Failed
          token: ${{secrets.GITHUB_TOKEN}}
          assignees: ${{github.actor}}
          labels: Build failed, help needed
          body: Workflow failed for commit ${{github.sha}}

