name: trips

on:
  push:
    paths:
      - apis/trips/**
      - .github/workflows/trips.yml
  pull_request:
    branches: [ master ]
    paths:
      - apis/trips/**
      - .github/workflows/trips.yml

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run: 
        shell: bash
        working-directory: apis/trips
    steps:
    - uses: actions/checkout@v2
      
    - name: Setup go
      uses: actions/setup-go@v2.0.3
        
    - name: install dependencies 
      run: go get
    
    - name: Test
      run: go test ./tests
        
    - uses: nashmaniac/create-issue-action@v1.1
      if: ${{ failure() }} # only run when this job is failed.
      name: Create Issue Action
      with:
          title: Build Failed trips
          token: ${{secrets.GITHUB_TOKEN}}
          assignees: ${{github.actor}}
          labels: Build failed, help needed
          body: Workflow failed for commit ${{github.sha}}

  docker-build-and-deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: build-and-test
    env:
      registery: openhackw1l12y49acr.azurecr.io
      app: devopsoh/api-trips
      dockerpath: apis/trips
    
    steps:
    # checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@master
            
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ env.registery }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - run: |
        docker build ${{ env.dockerpath }} -t ${{ env.registery }}/${{ env.app }}:${{ github.run_number }}
        docker push ${{ env.registery }}/${{ env.app }}:${{ github.run_number }}
  
    - uses: nashmaniac/create-issue-action@v1.1
      if: ${{ failure() }} # only run when this job is failed.
      name: Create Issue Action
      with:
          title: Build Failed trips
          token: ${{secrets.GITHUB_TOKEN}}
          assignees: ${{github.actor}}
          labels: Build failed, help needed
          body: Workflow failed for commit ${{github.sha}}
