name: Node.js CI

on:
  push:
    paths:
      - apis/userprofile/**
      - .github/userprofile/userprofile-workflow.yml
  pull_request:
    branches: [ master ]
    paths:
      - apis/userprofile/**
      - .github/workflows/userprofile-workflow.yml

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [8.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build and test
        run: |
          npm run build --if-present
          npm test 
