name: Node.js CI

on:
  push:
    branches: [ master ]
    paths:
      - apis/poi/**
      - .github/userprofile/userprofile-workflow.yml
  pull_request:
    branches: [ master ]
    paths:
      - apis/userprofile/**
      - .github/workflows/userprofile-workflow.yml

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
      - name: npm install, build and test
        run: |
          npm install
          npm run build --if-present
          npm test