name: UserJava

on:
  push:
    branches: [ rautttus/TestUserProfile ]
    paths:
      - apis/user-java/**
      - .github/workflows/userjava.yml
  pull_request:
    branches: [ master ]
    paths:
      - apis/user-java/**
      - .github/workflows/userjava.yml

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults: 
      run:
        shell: bash 
        working-directory: apis/user-java
    steps:
    - uses: actions/checkout@v2
      
    - name: Setup Java-JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11 
        
    - name: Test
      run: mvn test

    - uses: nashmaniac/create-issue-action@v1.1
      if: ${{ failure() }} # only run when this job is failed.
      name: Create Issue Action
      with:
          title: Build UserJava Failed
          token: ${{secrets.GITHUB_TOKEN}}
          assignees: ${{github.actor}}
          labels: Build failed, help needed
          body: Workflow failed for commit ${{github.sha}}

  docker-build-and-deploy:
    if: github.ref == 'refs/heads/rautttus/TestUserProfile'
    runs-on: ubuntu-latest
    needs: build-and-test
    env:
      registery: openhackw1l12y49acr.azurecr.io
      app: devopsoh/api-user-java
      dockerpath: apis/user-java
    
    steps:
    # checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@master
            
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ env.registery }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - run: |
        docker build ${{ env.dockerpath }} -t ${{ env.registery }}/${{ env.app }}:${{ github.run_number }}
        docker push ${{ env.registery }}/${{ env.app }}:${{ github.run_number }}
  
    - uses: nashmaniac/create-issue-action@v1.1
      if: ${{ failure() }} # only run when this job is failed.
      name: Create Issue Action
      with:
          title: Docker Failed - User java
          token: ${{secrets.GITHUB_TOKEN}}
          assignees: ${{github.actor}}
          labels: Build failed, help needed
          body: Workflow failed for commit ${{github.sha}}
